import Mathlib

/-!
# Selecting the target even length

The final upper-bound step is an integer/parity argument: an even target
between the first and last members of a step-two interval is one of its
members.  This file makes that inference explicit.
-/

namespace LeanCo.SizeRamsey

/-- If an even `n` lies in the interval generated by adding an even offset
between `2` and `cycleLength - 2` to `2*r`, then such an offset exists
literally. -/
theorem exists_even_cycle_offset {n r cycleLength : ℕ} (hn : Even n)
    (hlower : 2 * r + 2 ≤ n)
    (hupper : n ≤ 2 * r + cycleLength - 2) :
    ∃ s : ℕ, Even s ∧ 2 ≤ s ∧ s ≤ cycleLength - 2 ∧ n = 2 * r + s := by
  obtain ⟨m, hm⟩ := hn
  have hn_eq : n = 2 * m := by omega
  have hrm : r ≤ m := by omega
  refine ⟨2 * (m - r), ⟨m - r, by omega⟩, ?_, ?_, ?_⟩ <;> omega

/-- Strict inequalities in the form appearing in the paper imply the weak
endpoint inequalities needed by `exists_even_cycle_offset`. -/
theorem exists_even_cycle_offset_of_strict {n r cycleLength : ℕ} (hn : Even n)
    (hcycle : Even cycleLength)
    (hlower : 2 * r + 2 < n)
    (hupper : n < 2 * r + cycleLength) :
    ∃ s : ℕ, Even s ∧ 2 ≤ s ∧ s ≤ cycleLength - 2 ∧ n = 2 * r + s := by
  apply exists_even_cycle_offset hn hlower.le
  obtain ⟨m, hm⟩ := hn
  obtain ⟨c, hc⟩ := hcycle
  omega

end LeanCo.SizeRamsey
