import LeanCo.Negami.StateSum
import Mathlib.Tactic.FinCases

/-!
# Boundary states and gluing (Sections 4–5)

The common boundary partition type is kept abstract.  It can be instantiated by
the finite lattice of set partitions of the boundary.  Only its block-count
and the block-count `ρ` of the equivalence relation generated by two
partitions enter the theorem.
-/

namespace LeanCo.Negami

open scoped BigOperators

/-- Negami data equipped with the partition induced on a finite boundary. -/
structure BoundaryData (P : Type) [Fintype P] [DecidableEq P]
    extends NegamiData where
  boundaryType : Finset Edge → P
  blocks : P → ℕ
  blocks_le_components : ∀ S, blocks (boundaryType S) ≤ components S

namespace BoundaryData

variable {P : Type} [Fintype P] [DecidableEq P]

/-- Components not meeting the boundary. -/
def internalComponents (K : BoundaryData P) (S : Finset K.Edge) : ℕ :=
  K.components S - K.blocks (K.boundaryType S)

/-- Degree of a pair of boundary states after gluing. -/
noncomputable def pairDegree (K H : BoundaryData P) (ρ : P → P → ℕ)
    (S : Finset K.Edge × Finset H.Edge) : Degree →₀ ℕ :=
  Finsupp.single 0
      (K.internalComponents S.1 + H.internalComponents S.2 +
        ρ (K.boundaryType S.1) (H.boundaryType S.2)) +
    Finsupp.single 1 (S.1.card + S.2.card) +
    Finsupp.single 2
      ((Nat.card K.Edge - S.1.card) + (Nat.card H.Edge - S.2.card))

/-- The same glued-state grading as an explicit tridegree. -/
noncomputable def pairTriDegree (K H : BoundaryData P) (ρ : P → P → ℕ)
    (S : Finset K.Edge × Finset H.Edge) : Tridegree :=
  ⟨K.internalComponents S.1 + H.internalComponents S.2 +
      ρ (K.boundaryType S.1) (H.boundaryType S.2),
    S.1.card + S.2.card,
    (Nat.card K.Edge - S.1.card) + (Nat.card H.Edge - S.2.card)⟩

/-- The based triply graded object whose homogeneous basis consists of pairs
of boundary states, with the gluing correction in component degree. -/
noncomputable abbrev pairingObject (K H : BoundaryData P) (ρ : P → P → ℕ) :
    GradedObject where
  Basis := Finset K.Edge × Finset H.Edge
  fintypeBasis := inferInstance
  degree := pairTriDegree K H ρ

/-- The polynomial obtained by the categorical boundary pairing. -/
noncomputable def pairingPolynomial (K H : BoundaryData P) (ρ : P → P → ℕ)
    (R : Type*) [CommSemiring R] : MvPolynomial Degree R :=
  ∑ S : Finset K.Edge × Finset H.Edge,
    MvPolynomial.monomial (pairDegree K H ρ S) 1

/-- Concrete combinatorial facts supplied when two boundary graphs are glued:
states split uniquely, edge counts add, and the component formula of Lemma 4.3
holds. -/
structure Gluing (G : NegamiData) (K H : BoundaryData P) (ρ : P → P → ℕ) where
  states : Finset G.Edge ≃ Finset K.Edge × Finset H.Edge
  selected_card : ∀ S : Finset G.Edge,
    S.card = (states S).1.card + (states S).2.card
  edge_card : Nat.card G.Edge = Nat.card K.Edge + Nat.card H.Edge
  componentEquiv : ∀ S : Finset G.Edge,
    Fin (G.components S) ≃
      Fin (K.internalComponents (states S).1) ⊕
        (Fin (H.internalComponents (states S).2) ⊕
          Fin (ρ (K.boundaryType (states S).1) (H.boundaryType (states S).2)))

/-- Component counting is a consequence of the component decomposition, not
an assumed numerical identity. -/
theorem Gluing.component_formula {G : NegamiData} {K H : BoundaryData P}
    {ρ : P → P → ℕ} (W : Gluing G K H ρ) (S : Finset G.Edge) :
    G.components S =
      K.internalComponents (W.states S).1 + H.internalComponents (W.states S).2 +
        ρ (K.boundaryType (W.states S).1) (H.boundaryType (W.states S).2) := by
  have h := Fintype.card_congr (W.componentEquiv S)
  simpa only [Fintype.card_fin, Fintype.card_sum, Nat.add_assoc] using h

/-- Lemma 4.3 plus additivity of selected/unselected edge counts gives equality
of the complete tridegree. -/
theorem Gluing.degree_eq_pair {G : NegamiData} {K H : BoundaryData P}
    {ρ : P → P → ℕ} (W : Gluing G K H ρ) (S : Finset G.Edge) :
    G.degree S = pairDegree K H ρ (W.states S) := by
  classical
  have hK : (W.states S).1.card ≤ Nat.card K.Edge := by
    simpa only [Nat.card_eq_fintype_card] using Finset.card_le_univ (W.states S).1
  have hH : (W.states S).2.card ≤ Nat.card H.Edge := by
    simpa only [Nat.card_eq_fintype_card] using Finset.card_le_univ (W.states S).2
  ext i
  fin_cases i <;> simp [NegamiData.degree, pairDegree, W.component_formula,
    W.selected_card, W.edge_card, -Nat.card_eq_fintype_card] ; omega

/-- The state splitting preserves the explicit triply graded degrees. -/
theorem Gluing.triDegree_eq_pair {G : NegamiData} {K H : BoundaryData P}
    {ρ : P → P → ℕ} (W : Gluing G K H ρ) (S : Finset G.Edge) :
    G.triDegree S = pairTriDegree K H ρ (W.states S) := by
  classical
  have hK : (W.states S).1.card ≤ Nat.card K.Edge := by
    simpa only [Nat.card_eq_fintype_card] using Finset.card_le_univ (W.states S).1
  have hH : (W.states S).2.card ≤ Nat.card H.Edge := by
    simpa only [Nat.card_eq_fintype_card] using Finset.card_le_univ (W.states S).2
  apply Tridegree.ext
  · exact W.component_formula S
  · exact W.selected_card S
  · change Nat.card G.Edge - S.card =
      (Nat.card K.Edge - (W.states S).1.card) +
        (Nat.card H.Edge - (W.states S).2.card)
    rw [W.edge_card, W.selected_card]
    omega

/-- Theorem 4.5 at the categorical level: gluing induces an honest
degree-preserving equivalence of finite based graded objects. -/
noncomputable def Gluing.objectEquiv {G : NegamiData}
    {K H : BoundaryData P} {ρ : P → P → ℕ} (W : Gluing G K H ρ) :
    GradedObject.Equiv G.stateObject (pairingObject K H ρ) where
  basisEquiv := W.states
  degree_eq S := (W.triDegree_eq_pair S).symm

/-- Decategorifying the object-level gluing equivalence gives equality of
all scalar Hilbert state sums. -/
theorem Gluing.hilbert_gluing {G : NegamiData} {K H : BoundaryData P}
    {ρ : P → P → ℕ} (W : Gluing G K H ρ)
    {R : Type*} [CommSemiring R] (t x y : R) :
    G.stateObject.hilbert t x y = (pairingObject K H ρ).hilbert t x y :=
  W.objectEquiv.hilbert_eq t x y

/-- Theorem 4.5: the object-level gluing formula, expressed as equality of
Hilbert polynomials (and hence of every finite graded multiplicity). -/
theorem polynomial_gluing {G : NegamiData} {K H : BoundaryData P}
    {ρ : P → P → ℕ} (W : Gluing G K H ρ)
    (R : Type*) [CommSemiring R] :
    G.polynomial R = pairingPolynomial K H ρ R := by
  classical
  rw [NegamiData.polynomial, pairingPolynomial]
  exact Fintype.sum_equiv W.states _ _ fun S ↦ by
    rw [W.degree_eq_pair S]

/-- The boundary-state object of type `π`, represented by its graded
multiplicity function. -/
noncomputable def boundaryMultiplicity (K : BoundaryData P) (π : P)
    (d : Degree →₀ ℕ) : ℕ :=
  ∑ S : Finset K.Edge,
    if K.boundaryType S = π ∧
      d = Finsupp.single 0 (K.internalComponents S) +
          Finsupp.single 1 S.card +
          Finsupp.single 2 (Nat.card K.Edge - S.card)
    then 1 else 0

end BoundaryData
end LeanCo.Negami
