import LeanCo.Negami.ConcreteBoundary
import LeanCo.Negami.BoundaryQuotient
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Finite
import Mathlib.Data.Setoid.Basic

/-!
# Concrete boundary quotients

Vertices whose boundary labels lie in the same block of `α` are identified.
The generated equivalence relation is used deliberately: it exposes the
transitive closure that occurs in the definition of `ρ`.
-/

namespace LeanCo.Negami
namespace BoundaryMultigraph

variable (K : BoundaryMultigraph)

/-- The elementary vertex identifications prescribed by a boundary
partition. -/
def boundaryIdentification (α : FinitePartition K.Boundary) :
    K.graph.Vertex → K.graph.Vertex → Prop :=
  fun u v ↦ ∃ i j, K.boundaryEmbedding i = u ∧
    K.boundaryEmbedding j = v ∧ α.toSetoid i j

/-- The equivalence relation generated by the requested boundary
identifications. -/
def boundaryQuotientSetoid (α : FinitePartition K.Boundary) :
    Setoid K.graph.Vertex :=
  Relation.EqvGen.setoid (K.boundaryIdentification α)

noncomputable local instance boundaryQuotientVertexDecidableEq
    (α : FinitePartition K.Boundary) :
    DecidableEq (Quotient (K.boundaryQuotientSetoid α)) :=
  @Quotient.decidableEq _ (K.boundaryQuotientSetoid α)
    (fun _ _ ↦ Classical.propDecidable _)

/-- The quotient map on vertices. -/
noncomputable abbrev boundaryQuotientVertex
    (α : FinitePartition K.Boundary) (v : K.graph.Vertex) :
    Quotient (K.boundaryQuotientSetoid α) :=
  @Quotient.mk' _ (K.boundaryQuotientSetoid α) v

/-- The graph `K/α`. Edge labels are unchanged and endpoint pairs are mapped
through the vertex quotient. -/
noncomputable abbrev quotientGraph
    (α : FinitePartition K.Boundary) : FiniteMultigraph where
  Vertex := Quotient (K.boundaryQuotientSetoid α)
  Edge := K.graph.Edge
  vertexFintype := Fintype.ofFinite _
  vertexDecidableEq := boundaryQuotientVertexDecidableEq K α
  edgeFintype := K.graph.edgeFintype
  edgeDecidableEq := K.graph.edgeDecidableEq
  ends e := Sym2.map (K.boundaryQuotientVertex α) (K.graph.ends e)

/-- Quotienting vertices does not change the state set. -/
def quotientStateEquiv (α : FinitePartition K.Boundary) :
    Finset (K.quotientGraph α).Edge ≃ Finset K.graph.Edge :=
  Equiv.refl _

theorem quotientStateEquiv_apply (α : FinitePartition K.Boundary)
    (S : Finset (K.quotientGraph α).Edge) :
    K.quotientStateEquiv α S = S := rfl

theorem quotientStateEquiv_card (α : FinitePartition K.Boundary)
    (S : Finset (K.quotientGraph α).Edge) :
    S.card = (K.quotientStateEquiv α S).card := rfl

theorem quotientGraph_edge_card (α : FinitePartition K.Boundary) :
    Nat.card (K.quotientGraph α).Edge = Nat.card K.graph.Edge := rfl

/-- Every requested boundary identification is an equality in the quotient. -/
theorem boundaryQuotientVertex_eq (α : FinitePartition K.Boundary)
    {i j : K.Boundary} (hij : α.toSetoid i j) :
    K.boundaryQuotientVertex α (K.boundaryEmbedding i) =
      K.boundaryQuotientVertex α (K.boundaryEmbedding j) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ ⟨i, j, rfl, rfl, hij⟩

/-- Connectivity on original vertices after adding the identifications `α`.
Using whole original connected paths as generators makes the subsequent
component decomposition transparent. -/
def quotientConnectivity (α : FinitePartition K.Boundary)
    (S : Finset K.graph.Edge) : K.graph.Vertex → K.graph.Vertex → Prop :=
  Relation.EqvGen (fun u v ↦
    (K.graph.spanningGraph S).Reachable u v ∨ K.boundaryIdentification α u v)

theorem quotientConnectivity_trans (α : FinitePartition K.Boundary)
    (S : Finset K.graph.Edge) {u v w : K.graph.Vertex}
    (huv : K.quotientConnectivity α S u v)
    (hvw : K.quotientConnectivity α S v w) :
    K.quotientConnectivity α S u w :=
  Relation.EqvGen.trans u v w huv hvw

theorem quotientConnectivity_of_vertex_eq
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex}
    (h : K.boundaryQuotientVertex α u = K.boundaryQuotientVertex α v) :
    K.quotientConnectivity α S u v := by
  apply Relation.EqvGen.mono (fun a b hab ↦ Or.inr hab)
  exact Quotient.exact h

theorem quotientConnectivity_of_quotient_adj
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex}
    (huv : ((K.quotientGraph α).spanningGraph S).Adj
      (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v)) :
    K.quotientConnectivity α S u v := by
  classical
  change (SimpleGraph.fromEdgeSet
    (↑(S.image (K.quotientGraph α).ends))).Adj
      (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v) at huv
  rw [SimpleGraph.fromEdgeSet_adj] at huv
  rcases Finset.mem_image.mp huv.1 with ⟨e, he, hp⟩
  induction hEnds : K.graph.ends e using Sym2.inductionOn with
  | _ x y =>
    have hp' : s(K.boundaryQuotientVertex α x,
        K.boundaryQuotientVertex α y) =
        s(K.boundaryQuotientVertex α u,
          K.boundaryQuotientVertex α v) := by
      simpa [quotientGraph, hEnds, Sym2.map_mk] using hp
    have hxy : (K.graph.spanningGraph S).Reachable x y := by
      by_cases h : x = y
      · subst y
        exact SimpleGraph.Reachable.refl x
      · apply SimpleGraph.Adj.reachable
        change (SimpleGraph.fromEdgeSet (↑(S.image K.graph.ends))).Adj x y
        rw [SimpleGraph.fromEdgeSet_adj]
        exact ⟨Finset.mem_image.mpr ⟨e, he, hEnds⟩, h⟩
    rcases Sym2.eq_iff.mp hp' with h | h
    · apply K.quotientConnectivity_trans α S
      · exact K.quotientConnectivity_of_vertex_eq α S h.1.symm
      · apply K.quotientConnectivity_trans α S
        · exact Relation.EqvGen.rel _ _ (Or.inl hxy)
        · exact K.quotientConnectivity_of_vertex_eq α S h.2
    · apply K.quotientConnectivity_trans α S
      · exact K.quotientConnectivity_of_vertex_eq α S h.2.symm
      · apply K.quotientConnectivity_trans α S
        · exact Relation.EqvGen.rel _ _ (Or.inl hxy.symm)
        · exact K.quotientConnectivity_of_vertex_eq α S h.1

theorem quotientConnectivity_of_quotient_reachable
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex}
    (huv : ((K.quotientGraph α).spanningGraph S).Reachable
      (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v)) :
    K.quotientConnectivity α S u v := by
  rw [SimpleGraph.reachable_iff_reflTransGen] at huv
  let q := K.boundaryQuotientVertex α
  have lift : ∀ {a b}, Relation.ReflTransGen
      ((K.quotientGraph α).spanningGraph S).Adj a b →
      ∀ x y, q x = a → q y = b → K.quotientConnectivity α S x y := by
    intro a b hab
    induction hab using Relation.ReflTransGen.trans_induction_on with
    | refl a =>
        intro x y hx hy
        exact K.quotientConnectivity_of_vertex_eq α S (hx.trans hy.symm)
    | single hab =>
        intro x y hx hy
        change K.boundaryQuotientVertex α x = _ at hx
        change K.boundaryQuotientVertex α y = _ at hy
        apply K.quotientConnectivity_of_quotient_adj α S
        rw [hx, hy]
        exact hab
    | @trans a b c hab hbc ihab ihbc =>
        intro x z hx hz
        let y : K.graph.Vertex := Quotient.out b
        have hy : q y = b := Quotient.out_eq b
        exact K.quotientConnectivity_trans α S
          (ihab x y hx hy) (ihbc y z hy hz)
  exact lift huv u v rfl rfl

theorem quotient_reachable_of_original_reachable
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex} (huv : (K.graph.spanningGraph S).Reachable u v) :
    ((K.quotientGraph α).spanningGraph S).Reachable
      (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v) := by
  rcases huv with ⟨p⟩
  induction p with
  | nil => exact SimpleGraph.Reachable.refl _
  | @cons u v w huv p ih =>
      have hstep : ((K.quotientGraph α).spanningGraph S).Reachable
          (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v) := by
        classical
        by_cases hq : K.boundaryQuotientVertex α u = K.boundaryQuotientVertex α v
        · rw [hq]
        · apply SimpleGraph.Adj.reachable
          change (SimpleGraph.fromEdgeSet (↑(S.image K.graph.ends))).Adj u v at huv
          change (SimpleGraph.fromEdgeSet
            (↑(S.image (K.quotientGraph α).ends))).Adj
              (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v)
          rw [SimpleGraph.fromEdgeSet_adj] at huv ⊢
          rcases Finset.mem_image.mp huv.1 with ⟨e, he, hp⟩
          refine ⟨Finset.mem_image.mpr ⟨e, he, ?_⟩, hq⟩
          change Sym2.map (K.boundaryQuotientVertex α) (K.graph.ends e) = _
          rw [hp, Sym2.map_mk]
      exact hstep.trans ih

theorem quotient_reachable_of_quotientConnectivity
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex} (huv : K.quotientConnectivity α S u v) :
    ((K.quotientGraph α).spanningGraph S).Reachable
      (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v) := by
  induction huv with
  | rel u v h =>
      rcases h with h | ⟨i, j, rfl, rfl, hij⟩
      · exact K.quotient_reachable_of_original_reachable α S h
      · rw [K.boundaryQuotientVertex_eq α hij]
  | refl u => exact SimpleGraph.Reachable.refl _
  | symm u v _ ih => exact ih.symm
  | trans u v w _ _ ih₁ ih₂ => exact ih₁.trans ih₂

theorem quotient_reachable_iff_quotientConnectivity
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex} :
    ((K.quotientGraph α).spanningGraph S).Reachable
        (K.boundaryQuotientVertex α u) (K.boundaryQuotientVertex α v) ↔
      K.quotientConnectivity α S u v :=
  ⟨K.quotientConnectivity_of_quotient_reachable α S,
    K.quotient_reachable_of_quotientConnectivity α S⟩

def quotientConnectivitySetoid (α : FinitePartition K.Boundary)
    (S : Finset K.graph.Edge) : Setoid K.graph.Vertex :=
  Relation.EqvGen.setoid (fun u v ↦
    (K.graph.spanningGraph S).Reachable u v ∨ K.boundaryIdentification α u v)

/-- A class for generated connectivity maps to the corresponding connected
component in the concrete quotient graph. -/
noncomputable def generatedComponentMap
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Quotient (K.quotientConnectivitySetoid α S) →
      ((K.quotientGraph α).spanningGraph S).ConnectedComponent := by
  refine Quotient.lift (fun v ↦
    ((K.quotientGraph α).spanningGraph S).connectedComponentMk
      (K.boundaryQuotientVertex α v)) ?_
  intro u v huv
  apply SimpleGraph.ConnectedComponent.sound
  exact K.quotient_reachable_of_quotientConnectivity α S huv

theorem generatedComponentMap_surjective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Surjective (K.generatedComponentMap α S) := by
  intro c
  induction c using SimpleGraph.ConnectedComponent.ind with
  | _ q =>
    induction q using Quotient.inductionOn with
    | _ v =>
      exact ⟨@Quotient.mk' _ (K.quotientConnectivitySetoid α S) v, by
        change ((K.quotientGraph α).spanningGraph S).connectedComponentMk
            (K.boundaryQuotientVertex α v) = _
        rfl⟩

theorem generatedComponentMap_injective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Injective (K.generatedComponentMap α S) := by
  intro c d hcd
  induction c using Quotient.inductionOn with
  | _ u =>
    induction d using Quotient.inductionOn with
    | _ v =>
      apply Quotient.sound
      apply K.quotientConnectivity_of_quotient_reachable α S
      apply SimpleGraph.ConnectedComponent.exact
      change ((K.quotientGraph α).spanningGraph S).connectedComponentMk
          (K.boundaryQuotientVertex α u) =
        ((K.quotientGraph α).spanningGraph S).connectedComponentMk
          (K.boundaryQuotientVertex α v) at hcd
      exact hcd

/-- Connected components of the explicit quotient graph are exactly the
classes of original vertices under generated state connectivity and boundary
identification. -/
noncomputable def generatedComponentEquiv
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Quotient (K.quotientConnectivitySetoid α S) ≃
      ((K.quotientGraph α).spanningGraph S).ConnectedComponent :=
  Equiv.ofBijective (K.generatedComponentMap α S)
    ⟨K.generatedComponentMap_injective α S,
      K.generatedComponentMap_surjective α S⟩

theorem quotientGraph_components_as_generated_classes
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    (K.quotientGraph α).components S =
      Nat.card (Quotient (K.quotientConnectivitySetoid α S)) := by
  unfold FiniteMultigraph.components
  exact (Nat.card_congr (K.generatedComponentEquiv α S)).symm

/-- Elementary identifications of original state-components induced by `α`.
The source boundary partition is already absorbed because boundary labels are
sent to their connected components. -/
def stateComponentIdentification (α : FinitePartition K.Boundary)
    (S : Finset K.graph.Edge) :
    (K.graph.spanningGraph S).ConnectedComponent →
      (K.graph.spanningGraph S).ConnectedComponent → Prop :=
  fun c d ↦ ∃ i j, α.toSetoid i j ∧
    (K.graph.spanningGraph S).connectedComponentMk (K.boundaryEmbedding i) = c ∧
    (K.graph.spanningGraph S).connectedComponentMk (K.boundaryEmbedding j) = d

def stateComponentQuotientSetoid (α : FinitePartition K.Boundary)
    (S : Finset K.graph.Edge) :
    Setoid (K.graph.spanningGraph S).ConnectedComponent :=
  Relation.EqvGen.setoid (K.stateComponentIdentification α S)

/-- Collapse original vertices first to state-components and then impose the
boundary relation. -/
noncomputable def generatedToStateComponentQuotient
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Quotient (K.quotientConnectivitySetoid α S) →
      Quotient (K.stateComponentQuotientSetoid α S) := by
  refine Quotient.lift (fun v ↦ @Quotient.mk'
    (K.graph.spanningGraph S).ConnectedComponent
    (K.stateComponentQuotientSetoid α S)
    ((K.graph.spanningGraph S).connectedComponentMk v)) ?_
  intro u v huv
  apply Quotient.sound
  induction huv with
  | rel u v h =>
      rcases h with h | ⟨i, j, hi, hj, hij⟩
      · have hc : (K.graph.spanningGraph S).connectedComponentMk u =
            (K.graph.spanningGraph S).connectedComponentMk v :=
          SimpleGraph.ConnectedComponent.sound h
        rw [hc]
      · subst u
        subst v
        exact Relation.EqvGen.rel _ _ ⟨i, j, hij, rfl, rfl⟩
  | refl u => exact Relation.EqvGen.refl _
  | symm u v _ ih => exact ih.symm
  | trans u v w _ _ ih₁ ih₂ =>
      change Relation.EqvGen (K.stateComponentIdentification α S)
        ((K.graph.spanningGraph S).connectedComponentMk u)
        ((K.graph.spanningGraph S).connectedComponentMk w)
      exact Relation.EqvGen.trans _
        ((K.graph.spanningGraph S).connectedComponentMk v) _ ih₁ ih₂

theorem generatedToStateComponentQuotient_surjective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Surjective (K.generatedToStateComponentQuotient α S) := by
  intro q
  induction q using Quotient.inductionOn with
  | _ c =>
    induction c using SimpleGraph.ConnectedComponent.ind with
    | _ v =>
      exact ⟨@Quotient.mk' _ (K.quotientConnectivitySetoid α S) v, rfl⟩

/-- A generated relation between state-components lifts to generated
connectivity between any chosen vertex representatives. -/
theorem quotientConnectivity_of_stateComponentEqvGen
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {u v : K.graph.Vertex}
    (h : Relation.EqvGen (K.stateComponentIdentification α S)
      ((K.graph.spanningGraph S).connectedComponentMk u)
      ((K.graph.spanningGraph S).connectedComponentMk v)) :
    K.quotientConnectivity α S u v := by
  let C := (K.graph.spanningGraph S).ConnectedComponent
  have lift : ∀ {c d : C}, Relation.EqvGen
      (K.stateComponentIdentification α S) c d →
      ∀ x y, (K.graph.spanningGraph S).connectedComponentMk x = c →
        (K.graph.spanningGraph S).connectedComponentMk y = d →
        K.quotientConnectivity α S x y := by
    intro c d hcd
    induction hcd with
    | rel c d hcd =>
        intro x y hx hy
        rcases hcd with ⟨i, j, hij, hi, hj⟩
        have hxi : (K.graph.spanningGraph S).Reachable x
            (K.boundaryEmbedding i) := by
          apply SimpleGraph.ConnectedComponent.exact
          exact hx.trans hi.symm
        have hjy : (K.graph.spanningGraph S).Reachable
            (K.boundaryEmbedding j) y := by
          apply SimpleGraph.ConnectedComponent.exact
          exact hj.trans hy.symm
        apply K.quotientConnectivity_trans α S
        · exact Relation.EqvGen.rel _ _ (Or.inl hxi)
        · apply K.quotientConnectivity_trans α S
          · exact Relation.EqvGen.rel _ _ (Or.inr ⟨i, j, rfl, rfl, hij⟩)
          · exact Relation.EqvGen.rel _ _ (Or.inl hjy)
    | refl c =>
        intro x y hx hy
        exact Relation.EqvGen.rel _ _ (Or.inl
          (SimpleGraph.ConnectedComponent.exact (hx.trans hy.symm)))
    | symm c d _ ih =>
        intro x y hx hy
        exact (ih y x hy hx).symm
    | trans c d e _ _ ih₁ ih₂ =>
        intro x z hx hz
        induction d using SimpleGraph.ConnectedComponent.ind with
        | _ y =>
          exact K.quotientConnectivity_trans α S
            (ih₁ x y hx rfl) (ih₂ y z rfl hz)
  exact lift h u v rfl rfl

theorem generatedToStateComponentQuotient_injective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Injective (K.generatedToStateComponentQuotient α S) := by
  intro q r hqr
  induction q using Quotient.inductionOn with
  | _ u =>
    induction r using Quotient.inductionOn with
    | _ v =>
      apply Quotient.sound
      apply K.quotientConnectivity_of_stateComponentEqvGen α S
      exact Quotient.exact hqr

/-- Quotienting vertices by state connectivity and boundary identifications
is equivalent to quotienting the original state-component set by the induced
boundary identifications. -/
noncomputable def generatedStateComponentEquiv
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Quotient (K.quotientConnectivitySetoid α S) ≃
      Quotient (K.stateComponentQuotientSetoid α S) :=
  Equiv.ofBijective (K.generatedToStateComponentQuotient α S)
    ⟨K.generatedToStateComponentQuotient_injective α S,
      K.generatedToStateComponentQuotient_surjective α S⟩

/-- Original state-components not meeting the boundary. -/
abbrev internalStateComponent (S : Finset K.graph.Edge) :=
  {c : (K.graph.spanningGraph S).ConnectedComponent //
    c ∉ Set.range (K.boundaryComponentMap S)}

noncomputable instance internalStateComponentFintype
    (S : Finset K.graph.Edge) : Fintype (K.internalStateComponent S) := by
  classical
  unfold internalStateComponent
  exact Fintype.ofFinite _

/-- The concrete internal-component type has the numerical size used by
`BoundaryData.internalComponents`. -/
theorem card_internalStateComponent (S : Finset K.graph.Edge) :
    Nat.card (K.internalStateComponent S) =
      K.graph.components S - FinitePartition.blocks (K.boundaryPartition S) := by
  classical
  rw [Nat.card_eq_fintype_card]
  unfold FiniteMultigraph.components FiniteMultigraph.omega
  have hcomponent : Nat.card (K.graph.StateComponent S) =
      Nat.card (K.graph.spanningGraph S).ConnectedComponent := rfl
  rw [hcomponent]
  unfold FinitePartition.blocks
  rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card]
  unfold internalStateComponent
  rw [Fintype.card_subtype_compl]
  have hrange : Fintype.card
      (Set.range (K.boundaryComponentMap S)) =
      Fintype.card (Quotient (K.boundaryPartition S).toSetoid) := by
    exact (Fintype.card_congr
      (Equiv.ofInjective (K.boundaryComponentMap S)
        (K.boundaryComponentMap_injective S))).symm
  rw [hrange]

/-- A generated component identification preserves the property of meeting
the boundary. -/
theorem stateComponentEqvGen_boundary_iff
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {c d : (K.graph.spanningGraph S).ConnectedComponent}
    (h : Relation.EqvGen (K.stateComponentIdentification α S) c d) :
    (∃ i, (K.graph.spanningGraph S).connectedComponentMk
        (K.boundaryEmbedding i) = c) ↔
      ∃ j, (K.graph.spanningGraph S).connectedComponentMk
        (K.boundaryEmbedding j) = d := by
  induction h with
  | rel c d h =>
      rcases h with ⟨i, j, hij, hi, hj⟩
      exact ⟨fun _ ↦ ⟨j, hj⟩, fun _ ↦ ⟨i, hi⟩⟩
  | refl c => exact Iff.rfl
  | symm c d _ ih => exact ih.symm
  | trans c d e _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Equality of original state-components gives the relation represented by
the state-induced boundary partition. -/
theorem boundaryPartition_rel_of_component_eq
    (S : Finset K.graph.Edge) {i j : K.Boundary}
    (h : (K.graph.spanningGraph S).connectedComponentMk
        (K.boundaryEmbedding i) =
      (K.graph.spanningGraph S).connectedComponentMk
        (K.boundaryEmbedding j)) :
    (K.boundaryPartition S).toSetoid i j := by
  apply (K.boundaryPartition_rel S i j).mpr
  exact SimpleGraph.ConnectedComponent.exact h

/-- The generated relation on boundary-meeting state-components is exactly
the join of the imposed partition and the state-induced partition. -/
theorem stateComponentEqvGen_iff_join
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    (i j : K.Boundary) :
    Relation.EqvGen (K.stateComponentIdentification α S)
        ((K.graph.spanningGraph S).connectedComponentMk (K.boundaryEmbedding i))
        ((K.graph.spanningGraph S).connectedComponentMk (K.boundaryEmbedding j)) ↔
      (FinitePartition.join α (K.boundaryPartition S)).toSetoid i j := by
  classical
  rw [FinitePartition.join_rel]
  constructor
  · intro h
    let C := (K.graph.spanningGraph S).ConnectedComponent
    have lift : ∀ {c d : C},
        Relation.EqvGen (K.stateComponentIdentification α S) c d →
        ∀ a b,
          (K.graph.spanningGraph S).connectedComponentMk
              (K.boundaryEmbedding a) = c →
          (K.graph.spanningGraph S).connectedComponentMk
              (K.boundaryEmbedding b) = d →
          Relation.EqvGen (fun x y ↦
            α.toSetoid x y ∨ (K.boundaryPartition S).toSetoid x y) a b := by
      intro c d hcd
      induction hcd with
      | rel c d hcd =>
          intro a b ha hb
          rcases hcd with ⟨x, y, hxy, hx, hy⟩
          apply Relation.EqvGen.trans a x b
          · exact Relation.EqvGen.rel _ _ (Or.inr
              (K.boundaryPartition_rel_of_component_eq S (ha.trans hx.symm)))
          · apply Relation.EqvGen.trans x y b
            · exact Relation.EqvGen.rel _ _ (Or.inl hxy)
            · exact Relation.EqvGen.rel _ _ (Or.inr
                (K.boundaryPartition_rel_of_component_eq S (hy.trans hb.symm)))
      | refl c =>
          intro a b ha hb
          exact Relation.EqvGen.rel _ _ (Or.inr
            (K.boundaryPartition_rel_of_component_eq S (ha.trans hb.symm)))
      | symm c d hcd ih =>
          intro a b ha hb
          exact (ih b a hb ha).symm
      | trans c d e hcd hde ih₁ ih₂ =>
          intro a b ha hb
          obtain ⟨m, hm⟩ :=
            (K.stateComponentEqvGen_boundary_iff α S hcd).mp ⟨a, ha⟩
          exact Relation.EqvGen.trans a m b
            (ih₁ a m ha hm) (ih₂ m b hm hb)
    exact lift h i j rfl rfl
  · intro h
    induction h with
    | rel a b hab =>
        rcases hab with hab | hab
        · exact Relation.EqvGen.rel _ _ ⟨a, b, hab, rfl, rfl⟩
        · have hc : (K.graph.spanningGraph S).connectedComponentMk
              (K.boundaryEmbedding a) =
              (K.graph.spanningGraph S).connectedComponentMk
                (K.boundaryEmbedding b) := by
            apply SimpleGraph.ConnectedComponent.sound
            exact (K.boundaryPartition_rel S a b).mp hab
          rw [hc]
          exact Relation.EqvGen.refl _
    | refl a => exact Relation.EqvGen.refl _
    | symm a b _ ih => exact ih.symm
    | trans a b c _ _ ih₁ ih₂ =>
        exact Relation.EqvGen.trans _
          ((K.graph.spanningGraph S).connectedComponentMk
            (K.boundaryEmbedding b)) _ ih₁ ih₂

/-- Joined boundary blocks map into the quotient of state-components. -/
noncomputable def boundaryJoinToStateComponentQuotient
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Quotient (FinitePartition.join α (K.boundaryPartition S)).toSetoid →
      Quotient (K.stateComponentQuotientSetoid α S) := by
  refine Quotient.lift (fun i ↦ @Quotient.mk' _
    (K.stateComponentQuotientSetoid α S)
    ((K.graph.spanningGraph S).connectedComponentMk
      (K.boundaryEmbedding i))) ?_
  intro i j hij
  apply Quotient.sound
  exact (K.stateComponentEqvGen_iff_join α S i j).mpr hij

theorem boundaryJoinToStateComponentQuotient_injective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Injective (K.boundaryJoinToStateComponentQuotient α S) := by
  intro x y hxy
  induction x using Quotient.inductionOn with
  | _ i =>
    induction y using Quotient.inductionOn with
    | _ j =>
      apply Quotient.sound
      apply (K.stateComponentEqvGen_iff_join α S i j).mp
      exact Quotient.exact hxy

theorem stateComponentEqvGen_eq_of_not_boundary
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge)
    {c d : (K.graph.spanningGraph S).ConnectedComponent}
    (h : Relation.EqvGen (K.stateComponentIdentification α S) c d)
    (hc : ¬ ∃ i, (K.graph.spanningGraph S).connectedComponentMk
      (K.boundaryEmbedding i) = c) : c = d := by
  induction h with
  | rel c d h =>
      rcases h with ⟨i, j, hij, hi, hj⟩
      exact False.elim (hc ⟨i, hi⟩)
  | refl c => rfl
  | symm c d h ih =>
      have hc' : ¬ ∃ i, (K.graph.spanningGraph S).connectedComponentMk
          (K.boundaryEmbedding i) = c := by
        intro hc'
        exact hc ((K.stateComponentEqvGen_boundary_iff α S h).mp hc')
      exact (ih hc').symm
  | trans c d e h₁ h₂ ih₁ ih₂ =>
      have hcd : c = d := ih₁ hc
      have hd : ¬ ∃ i, (K.graph.spanningGraph S).connectedComponentMk
          (K.boundaryEmbedding i) = d := by simpa [hcd] using hc
      exact hcd.trans (ih₂ hd)

/-- The quotient of the state-component set splits into untouched internal
components and the blocks of the joined boundary partition. -/
noncomputable def stateComponentDecompositionMap
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    K.internalStateComponent S ⊕
        Quotient (FinitePartition.join α (K.boundaryPartition S)).toSetoid →
      Quotient (K.stateComponentQuotientSetoid α S)
  | Sum.inl c => @Quotient.mk' _ (K.stateComponentQuotientSetoid α S) c.1
  | Sum.inr q => K.boundaryJoinToStateComponentQuotient α S q

theorem stateComponentDecompositionMap_surjective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Surjective (K.stateComponentDecompositionMap α S) := by
  intro q
  induction q using Quotient.inductionOn with
  | _ c =>
    by_cases hc : c ∈ Set.range (K.boundaryComponentMap S)
    · rcases hc with ⟨x, rfl⟩
      induction x using Quotient.inductionOn with
      | _ i =>
        exact ⟨Sum.inr (@Quotient.mk' _
          (FinitePartition.join α (K.boundaryPartition S)).toSetoid i), rfl⟩
    · exact ⟨Sum.inl ⟨c, hc⟩, rfl⟩

theorem stateComponentDecompositionMap_injective
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    Function.Injective (K.stateComponentDecompositionMap α S) := by
  intro x y hxy
  cases x with
  | inl c =>
      cases y with
      | inl d =>
          have hval : c.1 = d.1 := by
            apply K.stateComponentEqvGen_eq_of_not_boundary α S (Quotient.exact hxy)
            intro hc
            rcases hc with ⟨i, hi⟩
            apply c.2
            refine ⟨@Quotient.mk' _ (K.boundaryPartition S).toSetoid i, ?_⟩
            exact hi
          exact congrArg Sum.inl (Subtype.ext hval)
      | inr q =>
          exfalso
          induction q using Quotient.inductionOn with
          | _ i =>
            have hrel := Quotient.exact hxy
            have hb := (K.stateComponentEqvGen_boundary_iff α S hrel).mpr
              ⟨i, rfl⟩
            rcases hb with ⟨j, hj⟩
            exact c.2 ⟨@Quotient.mk' _ (K.boundaryPartition S).toSetoid j, hj⟩
  | inr q =>
      cases y with
      | inl d =>
          exfalso
          induction q using Quotient.inductionOn with
          | _ i =>
            have hrel := Quotient.exact hxy
            have hb := (K.stateComponentEqvGen_boundary_iff α S hrel).mp
              ⟨i, rfl⟩
            rcases hb with ⟨j, hj⟩
            exact d.2 ⟨@Quotient.mk' _ (K.boundaryPartition S).toSetoid j, hj⟩
      | inr r =>
          congr 1
          exact K.boundaryJoinToStateComponentQuotient_injective α S hxy

noncomputable def stateComponentDecompositionEquiv
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    K.internalStateComponent S ⊕
        Quotient (FinitePartition.join α (K.boundaryPartition S)).toSetoid ≃
      Quotient (K.stateComponentQuotientSetoid α S) :=
  Equiv.ofBijective (K.stateComponentDecompositionMap α S)
    ⟨K.stateComponentDecompositionMap_injective α S,
      K.stateComponentDecompositionMap_surjective α S⟩

/-- Complete component-level decomposition for the concrete graph quotient. -/
noncomputable def quotientGraphComponentDecompositionEquiv
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    ((K.quotientGraph α).spanningGraph S).ConnectedComponent ≃
      K.internalStateComponent S ⊕
        Quotient (FinitePartition.join α (K.boundaryPartition S)).toSetoid :=
  (K.generatedComponentEquiv α S).symm |>.trans
    ((K.generatedStateComponentEquiv α S).trans
      (K.stateComponentDecompositionEquiv α S).symm)

/-- Concrete form of the boundary quotient component-count lemma. -/
theorem quotientGraph_component_formula
    (α : FinitePartition K.Boundary) (S : Finset K.graph.Edge) :
    (K.quotientGraph α).components S =
      (K.toBoundaryData.internalComponents S) +
        FinitePartition.rho α (K.boundaryPartition S) := by
  classical
  have hcard := Nat.card_congr (K.quotientGraphComponentDecompositionEquiv α S)
  rw [Nat.card_sum] at hcard
  rw [K.card_internalStateComponent S] at hcard
  exact hcard

/-- The explicit graph quotient realizes the abstract quotient witness used in
Lemma 5.1. -/
noncomputable def concreteQuotientWitness
    (α : FinitePartition K.Boundary) :
    BoundaryData.Quotient K.toBoundaryData
      (K.quotientGraph α).toNegamiData FinitePartition.rho α where
  states := K.quotientStateEquiv α
  selected_card := K.quotientStateEquiv_card α
  edge_card := K.quotientGraph_edge_card α
  componentEquiv := by
    intro S
    apply Fintype.equivOfCardEq
    simp only [Fintype.card_fin, Fintype.card_sum]
    change (K.quotientGraph α).components S =
      K.toBoundaryData.internalComponents S +
        FinitePartition.rho α (K.boundaryPartition S)
    exact K.quotientGraph_component_formula α S

/-- Fully concrete boundary quotient identity. -/
theorem polynomial_quotientGraph
    (α : FinitePartition K.Boundary) (R : Type*) [CommSemiring R] :
    (K.quotientGraph α).polynomial R =
      BoundaryData.quotientStateSum K.toBoundaryData
        FinitePartition.rho α R := by
  exact BoundaryData.polynomial_quotient (K.concreteQuotientWitness α) R

end BoundaryMultigraph
end LeanCo.Negami
