import Mathlib.Data.Fintype.Quotient
import Mathlib.SetTheory.Cardinal.Finite

/-! A computationally finite representation of partitions of a finite type. -/

namespace LeanCo.Negami

/-- Boolean equivalence relations, used so that the collection of all
partitions of a finite boundary is itself manifestly finite. -/
def IsEquivBool {B : Type*} (r : B → B → Bool) : Prop :=
  (∀ x, r x x = true) ∧
  (∀ x y, r x y = r y x) ∧
  (∀ x y z, r x y = true → r y z = true → r x z = true)

abbrev FinitePartition (B : Type*) := {r : B → B → Bool // IsEquivBool r}

noncomputable instance {B : Type*} [Finite B] : Fintype (FinitePartition B) :=
  Fintype.ofFinite _

namespace FinitePartition

variable {B : Type*}

def toSetoid (π : FinitePartition B) : Setoid B where
  r x y := π.1 x y = true
  iseqv := by
    refine ⟨π.2.1, ?_, ?_⟩
    · intro x y h
      rw [π.2.2.1]
      exact h
    · intro x y z hxy hyz
      exact π.2.2.2 x y z hxy hyz

noncomputable def blocks [Fintype B] (π : FinitePartition B) : ℕ := by
  exact Nat.card (Quotient π.toSetoid)

/-- The partition generated jointly by `π` and `σ`.  This is the join in the
refinement order used in the paper. -/
noncomputable def join [Fintype B] [DecidableEq B]
    (π σ : FinitePartition B) : FinitePartition B := by
  classical
  let r : B → B → Prop := fun x y ↦ π.toSetoid x y ∨ σ.toSetoid x y
  exact ⟨fun x y ↦ decide (Relation.EqvGen r x y),
    ⟨by
       intro x
       simp only [decide_eq_true_eq]
       exact Relation.EqvGen.refl x,
     by
       intro x y
       apply Bool.eq_iff_iff.mpr
       simp only [decide_eq_true_eq]
       constructor <;> exact fun h ↦ h.symm,
     by
       intro x y z hxy hyz
       simp only [decide_eq_true_eq] at hxy hyz ⊢
       exact Relation.EqvGen.trans x y z hxy hyz⟩⟩

theorem join_rel [Fintype B] [DecidableEq B]
    (π σ : FinitePartition B) (x y : B) :
    (join π σ).toSetoid x y ↔
      Relation.EqvGen (fun a b ↦ π.toSetoid a b ∨ σ.toSetoid a b) x y := by
  classical
  change (decide (Relation.EqvGen
    (fun a b ↦ π.toSetoid a b ∨ σ.toSetoid a b) x y)) = true ↔ _
  simp only [decide_eq_true_eq]

/-- The number `ρ(π,σ)` from the paper: the number of blocks after taking the
equivalence relation generated by both boundary partitions. -/
noncomputable def rho [Fintype B] [DecidableEq B]
    (π σ : FinitePartition B) : ℕ := blocks (join π σ)

theorem join_comm [Fintype B] [DecidableEq B]
    (π σ : FinitePartition B) : join π σ = join σ π := by
  classical
  apply Subtype.ext
  funext x y
  apply Bool.eq_iff_iff.mpr
  change (join π σ).toSetoid x y ↔ (join σ π).toSetoid x y
  rw [join_rel, join_rel]
  constructor
  · apply Relation.EqvGen.mono
    intro a b h
    exact h.elim Or.inr Or.inl
  · apply Relation.EqvGen.mono
    intro a b h
    exact h.elim Or.inr Or.inl

theorem rho_comm [Fintype B] [DecidableEq B]
    (π σ : FinitePartition B) : rho π σ = rho σ π := by
  rw [rho, rho, join_comm]

end FinitePartition
end LeanCo.Negami
