import LeanCo.Negami.FiniteGraph
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Finite
import Mathlib.Combinatorics.SimpleGraph.Operations
import Mathlib.Tactic

/-!
# The graphic rank inequality

For a finite labelled multigraph, this file proves
`|V| - omega(S) ≤ |S|`.  Parallel edges are handled by passing to the
finite image of endpoint pairs; loops are harmless because `fromEdgeSet`
discards diagonal pairs.
-/

namespace LeanCo.Negami

open SimpleGraph

namespace SimpleGraph

variable {V : Type*}

private noncomputable def mergeLabel (H : SimpleGraph V) (u v x : V) :
    H.ConnectedComponent := by
  classical
  exact if H.Reachable u x then H.connectedComponentMk v else H.connectedComponentMk x

private theorem mergeLabel_eq_of_adj (H : SimpleGraph V) (u v x y : V)
    (hxy : (H ⊔ edge u v).Adj x y) :
    mergeLabel H u v x = mergeLabel H u v y := by
  rw [sup_adj] at hxy
  rcases hxy with hxy | hxy
  · have hreach : H.Reachable u x ↔ H.Reachable u y := by
      constructor
      · exact fun h ↦ h.trans hxy.reachable
      · exact fun h ↦ h.trans hxy.symm.reachable
    have hcomp : H.connectedComponentMk x = H.connectedComponentMk y :=
      ConnectedComponent.connectedComponentMk_eq_of_adj hxy
    by_cases hx : H.Reachable u x <;> simp_all [mergeLabel]
  · rcases (edge_adj u v x y).mp hxy with ⟨(⟨rfl, rfl⟩ | ⟨rfl, rfl⟩), _⟩ <;>
      simp [mergeLabel]

private theorem mergeLabel_eq_of_reachable (H : SimpleGraph V) (u v x y : V)
    (hxy : (H ⊔ edge u v).Reachable x y) :
    mergeLabel H u v x = mergeLabel H u v y := by
  rw [reachable_iff_reflTransGen] at hxy
  induction hxy with
  | refl => rfl
  | tail hxy hyz ih => exact ih.trans (mergeLabel_eq_of_adj H u v _ _ hyz)

/-- Adding one simple edge reduces the component count by at most one. -/
theorem card_connectedComponent_le_sup_edge_add_one [Finite V]
    (H : SimpleGraph V) (u v : V) :
    Nat.card H.ConnectedComponent ≤
      Nat.card (H ⊔ edge u v).ConnectedComponent + 1 := by
  classical
  let q : H.ConnectedComponent → (H ⊔ edge u v).ConnectedComponent :=
    ConnectedComponent.map (Hom.ofLE le_sup_left)
  let a : H.ConnectedComponent := H.connectedComponentMk u
  let f : H.ConnectedComponent → (H ⊔ edge u v).ConnectedComponent ⊕ Unit :=
    fun c ↦ if c = a then Sum.inr () else Sum.inl (q c)
  have hf : Function.Injective f := by
    intro c d hcd
    by_cases hc : c = a
    · by_cases hd : d = a
      · exact hc.trans hd.symm
      · simp [f, hc, hd] at hcd
    · by_cases hd : d = a
      · simp [f, hc, hd] at hcd
      · have hq : q c = q d := by simpa [f, hc, hd] using hcd
        obtain ⟨x, rfl⟩ := Quot.exists_rep c
        obtain ⟨y, rfl⟩ := Quot.exists_rep d
        have hux : ¬ H.Reachable u x := by
          intro h
          exact hc (ConnectedComponent.sound h).symm
        have huy : ¬ H.Reachable u y := by
          intro h
          exact hd (ConnectedComponent.sound h).symm
        have hreach : (H ⊔ edge u v).Reachable x y := by
          apply ConnectedComponent.exact
          change (H ⊔ edge u v).connectedComponentMk x =
            (H ⊔ edge u v).connectedComponentMk y at hq
          exact hq
        have hn := mergeLabel_eq_of_reachable H u v x y hreach
        rw [mergeLabel, if_neg hux, mergeLabel, if_neg huy] at hn
        exact hn
  have hcard := Nat.card_le_card_of_injective f hf
  simpa [Nat.card_sum] using hcard

private noncomputable def botConnectedComponentEquiv :
    (⊥ : SimpleGraph V).ConnectedComponent ≃ V where
  toFun := Quot.lift id (by
    intro u v huv
    exact reachable_bot.mp huv)
  invFun v := (⊥ : SimpleGraph V).connectedComponentMk v
  left_inv c := by
    induction c using ConnectedComponent.ind with
    | _ v => rfl
  right_inv v := rfl

/-- A graph generated by `m` endpoint pairs has rank at most `m`. -/
theorem card_vertex_le_card_connectedComponent_add_card_fromEdgeSet
    [Finite V] (T : Finset (Sym2 V)) :
    Nat.card V ≤ Nat.card (SimpleGraph.fromEdgeSet (↑T : Set (Sym2 V))).ConnectedComponent +
      T.card := by
  classical
  induction T using Finset.induction_on with
  | empty =>
      simpa using (Nat.card_congr (botConnectedComponentEquiv (V := V))).symm.le
  | @insert e T he ih =>
      induction e using Sym2.inductionOn with
      | _ u v =>
          let H := SimpleGraph.fromEdgeSet (↑T : Set (Sym2 V))
          have hc := card_connectedComponent_le_sup_edge_add_one H u v
          have hgraph :
              SimpleGraph.fromEdgeSet (↑(insert s(u, v) T) : Set (Sym2 V)) =
                H ⊔ edge u v := by
            rw [Finset.coe_insert, Set.insert_eq, SimpleGraph.fromEdgeSet_union]
            exact sup_comm _ _
          calc
            Nat.card V ≤ Nat.card H.ConnectedComponent + T.card := ih
            _ ≤ (Nat.card (H ⊔ edge u v).ConnectedComponent + 1) + T.card :=
              Nat.add_le_add_right hc T.card
            _ = Nat.card
                  (SimpleGraph.fromEdgeSet (↑(insert s(u, v) T) : Set (Sym2 V))).ConnectedComponent +
                (insert s(u, v) T).card := by
              rw [hgraph, Finset.card_insert_of_notMem he]
              omega

end SimpleGraph

namespace FiniteMultigraph

variable (G : FiniteMultigraph)

/-- The graphic-rank inequality before subtraction. -/
theorem card_vertex_le_omega_add_card (S : Finset G.Edge) :
    Nat.card G.Vertex ≤ G.omega S + S.card := by
  classical
  have h := SimpleGraph.card_vertex_le_card_connectedComponent_add_card_fromEdgeSet
    (V := G.Vertex) (S.image G.ends)
  change Nat.card G.Vertex ≤ Nat.card (G.StateComponent S) + (S.image G.ends).card at h
  exact h.trans
    (Nat.add_le_add_left (Finset.card_image_le : (S.image G.ends).card ≤ S.card) _)

/-- Every spanning state has rank at most its number of selected labelled
edges, including for loops and parallel edges. -/
theorem card_vertex_sub_omega_le_card (S : Finset G.Edge) :
    Nat.card G.Vertex - G.omega S ≤ S.card := by
  apply Nat.sub_le_iff_le_add.mpr
  simpa [Nat.add_comm] using G.card_vertex_le_omega_add_card S

end FiniteMultigraph

end LeanCo.Negami
